# Generated by Django 3.1.1 on 2020-09-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='label',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='label',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='roll_out',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='quiztaker',
            name='date_finished',
        ),
        migrations.RemoveField(
            model_name='quiztaker',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiztime',
            field=models.IntegerField(default=15),
        ),
    ]
