# Generated by Django 2.1.1 on 2020-09-23 19:07

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cquestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('question', ckeditor_uploader.fields.RichTextUploadingField()),
                ('constraints', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ctestcases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testinput', models.CharField(max_length=500)),
                ('testoutput', models.CharField(max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler.Cquestions')),
            ],
        ),
    ]
