# Generated by Django 2.1.1 on 2020-09-23 19:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cquestions',
            name='question',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
