# Generated by Django 2.1.1 on 2020-09-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0003_auto_20200924_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cquestions',
            name='constraints',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ctestcases',
            name='testinput',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ctestcases',
            name='testoutput',
            field=models.TextField(),
        ),
    ]
