# Generated by Django 2.1.1 on 2020-09-24 10:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0004_auto_20200924_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pyquestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('question', ckeditor.fields.RichTextField()),
                ('constraints', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pytestcases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testinput', models.TextField()),
                ('testoutput', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler.Pyquestions')),
            ],
        ),
    ]
