# Generated by Django 2.1.1 on 2020-09-24 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('compiler', '0005_pyquestions_pytestcases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pyscore', models.IntegerField(default=0)),
                ('cscore', models.IntegerField(default=0)),
            ],
        ),
    ]
