# Generated by Django 3.1.1 on 2020-09-25 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0007_pytrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pytrack',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler.pyquestions'),
        ),
    ]
