# Generated by Django 3.1.1 on 2020-09-26 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0009_auto_20200925_0942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
